# Generated by Django 4.2.10 on 2024-02-07 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('office_location', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('office_location', models.CharField(max_length=100)),
                ('personal_info', models.TextField()),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Waiting for Check in', 'Waiting for Check in'), ('Inside Building', 'Inside Building'), ('Checked Out', 'Checked Out')], default='Waiting for Check in', max_length=20)),
                ('employee_visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_management.employee')),
            ],
        ),
    ]
